apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-gateway
  namespace: istio-system
spec:
  secretName: ingress-cert
  renewBefore: 24h
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: '*.my-domain.com'
  dnsNames:
    - '*.my-domain.com'
